## Pandas wrap-up

In [34]:
import numpy as np
import pandas as pd

In [35]:
rowdata = {'col1': [414, 651], 'col2': [715,612]}
areacodes = pd.DataFrame(rowdata, index = ['WI', 'MN'])
areacodes['col3'] = [262,218]

areacodes

    col1  col2  col3
WI   414   715   262
MN   651   612   218

In [36]:
areacodes.index = areacodes['col1']

areacodes

      col1  col2  col3
col1
414    414   715   262
651    651   612   218

In [37]:
print(type(areacodes.index))

<class 'pandas.Index'>

In [38]:
orchard_output = areacodes
orchard_output.columns = ['apples','cherries','strawberries']
orchard_output

      apples  cherries  strawberries
col1
414      414       715           262
651      651       612           218

In [39]:
orchard_output['State'] = ['WI','MN']
orchard_output

      apples  cherries  strawberries State
col1
414      414       715           262    WI
651      651       612           218    MN

In [40]:
orchard_output.set_index('State') # also removes the column from the set of columns

# also could use orchard_output.index but will need to use drop to remove the column from the columns if not it will be two of the same columns 
# in the DataFrame

       apples  cherries  strawberries
State
WI        414       715           262
MN        651       612           218

In [41]:
orchard_output.groupby('apples').sum() # returning a new DataFrame, with an index of Apples

        cherries  strawberries State
apples
414          715           262    WI
651          612           218    MN

In [42]:
o = orchard_output
o

      apples  cherries  strawberries State
col1
414      414       715           262    WI
651      651       612           218    MN

In [43]:
o.set_index('State', inplace=True)

In [44]:
o

       apples  cherries  strawberries
State
WI        414       715           262
MN        651       612           218

In [45]:
o['Total Orchard Output'] = o['apples'] + o['cherries'] + o['strawberries']
o

       apples  cherries  strawberries  Total Orchard Output
State
WI        414       715           262                  1391
MN        651       612           218                  1481

In [46]:
o.groupby('Total Orchard Output')[['apples']].mean()

                      apples
Total Orchard Output
1391                   414.0
1481                   651.0

## examples using Northwind

In [47]:
nw = pd.read_csv('northwind_example.csv')
nw

     OrderID                    ProductName  UnitPrice  Quantity
0      10248                 Queso Cabrales       14.0        12
1      10248  Singaporean Hokkien Fried Mee        9.8        10
2      10248         Mozzarella di Giovanni       34.8         5
3      10249          Manjimup Dried Apples       42.4        40
4      10249                           Tofu       18.6         9
..       ...                            ...        ...       ...
495    10435         Mozzarella di Giovanni       27.8        10
496    10436         Gnocchi di nonna Alice       30.4        40
497    10436       Wimmers gute Semmelkndel       26.6        30
498    10436             Rhnbru Klosterbier        6.2        24
499    10436                      Spegesild        9.6         5

[500 rows x 4 columns]

## Which product is the highest selling by # of orders? Which is the lowest selling?

In [48]:
nw.groupby('ProductName')[['OrderID']].count().sort_values('OrderID',ascending=False)
# aggregation function lets you build a more complex set of aggregations,

                           OrderID
ProductName
Gorgonzola Telino               14
Mozzarella di Giovanni          14
Raclette Courdavault            14
Flotemysost                     13
Tarte au sucre                  13
...                            ...
Louisiana Hot Spiced Okra        1
Mishi Kobe Niku                  1
Queso Manchego La Pastora        1
Rogede sild                      1
Sirop d'rable                    1

[77 rows x 1 columns]

In [49]:
top_selling

NameError: name 'top_selling' is not defined

In [50]:
top_selling.head(3)

NameError: name 'top_selling' is not defined

In [51]:
top_selling[(top_selling['Order Count'] == 1)]

NameError: name 'top_selling' is not defined

## What was Total revenue? What was line-item revenue? What was revenue by product?

In [52]:
nw['LineTotal'] = nw['UnitPrice'] * nw['Quantity']
nw

     OrderID                    ProductName  UnitPrice  Quantity  LineTotal
0      10248                 Queso Cabrales       14.0        12      168.0
1      10248  Singaporean Hokkien Fried Mee        9.8        10       98.0
2      10248         Mozzarella di Giovanni       34.8         5      174.0
3      10249          Manjimup Dried Apples       42.4        40     1696.0
4      10249                           Tofu       18.6         9      167.4
..       ...                            ...        ...       ...        ...
495    10435         Mozzarella di Giovanni       27.8        10      278.0
496    10436         Gnocchi di nonna Alice       30.4        40     1216.0
497    10436       Wimmers gute Semmelkndel       26.6        30      798.0
498    10436             Rhnbru Klosterbier        6.2        24      148.8
499    10436                      Spegesild        9.6         5       48.0

[500 rows x 5 columns]

In [53]:
prod_by_rev = nw.groupby('ProductName')[['Quantity','LineTotal']].sum()
prod_by_rev.columns = ['Total Qty Sold','Total Product Revenue']

prod_by_rev

                                 Total Qty Sold  Total Product Revenue
ProductName
Alice Mutton                                331                10327.2
Aniseed Syrup                                80                  640.0
Boston Crab Meat                            256                 3763.2
Camembert Pierrot                           430                11696.0
Carnarvon Tigers                            106                 5300.0
...                                         ...                    ...
Uncle Bob's Organic Dried Pears              25                  600.0
Valkoinen suklaa                             70                  910.0
Vegie-spread                                209                 7335.9
Wimmers gute Semmelkndel                    161                 4282.6
Zaanse koeken                               101                  767.6

[77 rows x 2 columns]

In [54]:
print(prod_by_rev['Total Product Revenue'].sum()) # people use convention of df

297044.9

In [55]:
print(nw['LineTotal'].sum())

297044.9

In [56]:
prod_by_rev.sort_index(ascending=False)

                                 Total Qty Sold  Total Product Revenue
ProductName
Zaanse koeken                               101                  767.6
Wimmers gute Semmelkndel                    161                 4282.6
Vegie-spread                                209                 7335.9
Valkoinen suklaa                             70                  910.0
Uncle Bob's Organic Dried Pears              25                  600.0
...                                         ...                    ...
Carnarvon Tigers                            106                 5300.0
Camembert Pierrot                           430                11696.0
Boston Crab Meat                            256                 3763.2
Aniseed Syrup                                80                  640.0
Alice Mutton                                331                10327.2

[77 rows x 2 columns]

In [57]:
nw.sort_index(axis='columns')

     LineTotal  OrderID                    ProductName  Quantity  UnitPrice
0        168.0    10248                 Queso Cabrales        12       14.0
1         98.0    10248  Singaporean Hokkien Fried Mee        10        9.8
2        174.0    10248         Mozzarella di Giovanni         5       34.8
3       1696.0    10249          Manjimup Dried Apples        40       42.4
4        167.4    10249                           Tofu         9       18.6
..         ...      ...                            ...       ...        ...
495      278.0    10435         Mozzarella di Giovanni        10       27.8
496     1216.0    10436         Gnocchi di nonna Alice        40       30.4
497      798.0    10436       Wimmers gute Semmelkndel        30       26.6
498      148.8    10436             Rhnbru Klosterbier        24        6.2
499       48.0    10436                      Spegesild         5        9.6

[500 rows x 5 columns]

In [58]:
nw.sort_values('Quantity', ascending=False).head(10)

     OrderID                 ProductName  UnitPrice  Quantity  LineTotal
399    10398                  Pt chinois       19.2       120     2304.0
102    10286              Steeleye Stout       14.4       100     1440.0
334    10373      Escargots de Bourgogne       10.6        80      848.0
295    10359           Camembert Pierrot       27.2        80     2176.0
260    10345  Teatime Chocolate Biscuits        7.3        80      584.0
196    10324                Vegie-spread       35.1        80     2808.0
274    10351                Gula Malacca       15.5        77     1193.5
52     10267        Raclette Courdavault       44.0        70     3080.0
330    10372           Camembert Pierrot       27.2        70     1904.0
197    10324              Steeleye Stout       14.4        70     1008.0

In [59]:
# using rank

qty = nw[['Quantity']].rank(axis='rows')
nw.insert(4, 'Ranking by qty ordered', qty)
nw

,OrderID,ProductName,UnitPrice,Quantity,Ranking by qty ordered,LineTotal
0,10248,Queso Cabrales,14.0,12,142.5,168.0
1,10248,Singaporean Hokkien Fried Mee,9.8,10,108.5,98.0
2,10248,Mozzarella di Giovanni,34.8,5,35.5,174.0
3,10249,Manjimup Dried Apples,42.4,40,413.5,1696.0
4,10249,Tofu,18.6,9,82.5,167.4
...,...,...,...,...,...,...
495,10435,Mozzarella di Giovanni,27.8,10,108.5,278.0
496,10436,Gnocchi di nonna Alice,30.4,40,413.5,1216.0
497,10436,Wimmers gute Semmelkndel,26.6,30,355.5,798.0
498,10436,Rhnbru Klosterbier,6.2,24,302.5,148.8
499,10436,Spegesild,9.6,5,35.5,48.0

In [60]:
prod_by_rev

                                 Total Qty Sold  Total Product Revenue
ProductName
Alice Mutton                                331                10327.2
Aniseed Syrup                                80                  640.0
Boston Crab Meat                            256                 3763.2
Camembert Pierrot                           430                11696.0
Carnarvon Tigers                            106                 5300.0
...                                         ...                    ...
Uncle Bob's Organic Dried Pears              25                  600.0
Valkoinen suklaa                             70                  910.0
Vegie-spread                                209                 7335.9
Wimmers gute Semmelkndel                    161                 4282.6
Zaanse koeken                               101                  767.6

[77 rows x 2 columns]

In [61]:
prod_rank = prod_by_rev[['Total Product Revenue']].rank( axis='columns')
prod_rank.columns = ['Product Rank']
prod_rank # result looks weird just pretend everything is fine

                                 Product Rank
ProductName
Alice Mutton                              1.0
Aniseed Syrup                             1.0
Boston Crab Meat                          1.0
Camembert Pierrot                         1.0
Carnarvon Tigers                          1.0
...                                       ...
Uncle Bob's Organic Dried Pears           1.0
Valkoinen suklaa                          1.0
Vegie-spread                              1.0
Wimmers gute Semmelkndel                  1.0
Zaanse koeken                             1.0

[77 rows x 1 columns]

In [62]:
nw = pd.merge(nw, prod_rank, on='ProductName')
nw

,OrderID,ProductName,UnitPrice,Quantity,Ranking by qty ordered,LineTotal,Product Rank
0,10248,Queso Cabrales,14.0,12,142.5,168.0,1.0
1,10248,Singaporean Hokkien Fried Mee,9.8,10,108.5,98.0,1.0
2,10248,Mozzarella di Giovanni,34.8,5,35.5,174.0,1.0
3,10249,Manjimup Dried Apples,42.4,40,413.5,1696.0,1.0
4,10249,Tofu,18.6,9,82.5,167.4,1.0
...,...,...,...,...,...,...,...
495,10435,Mozzarella di Giovanni,27.8,10,108.5,278.0,1.0
496,10436,Gnocchi di nonna Alice,30.4,40,413.5,1216.0,1.0
497,10436,Wimmers gute Semmelkndel,26.6,30,355.5,798.0,1.0
498,10436,Rhnbru Klosterbier,6.2,24,302.5,148.8,1.0
499,10436,Spegesild,9.6,5,35.5,48.0,1.0

## Working with Matplotlib

In [68]:
import matplotlib as plt

In [69]:
byqty  = prod_by_rev[['Total Qty Sold']].sort_values('Total Qty Sold',ascending = False)

In [70]:
byqty = byqty.head(10)

In [71]:
plt.figure(figsize=(10,5))
plt.bar(byqty.index, byqty['Total Qty Sold'])
plt.show()

AttributeError: module 'matplotlib' has no attribute 'figure'

In [67]:
# alternative version

fig, ax = plt.subplots(figsize=(10,5))

ax.set_ticklabel(labels, rotation=45)

plt.bar(byqty.index, byqty['Total Qty Sold'])

plt.show()

AttributeError: module 'matplotlib' has no attribute 'subplots'