## Working with pandas

In [2]:
import numpy as np
import pandas as pd

In [3]:
list_x = [2,3,4,5,6,7]

x = pd.Series(list_x)

x

0    2
1    3
2    4
3    5
4    6
5    7
dtype: int64

In [4]:
y = pd.Series(list_x, index=[1,2,3,4,5,6]) # index can be named anything string or integer but don't do duplicates as when you call index it will be a problem

y

1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

In [5]:
dict_x = {
    '1': 2,
    '2': 3,
    '3': 4,
    '4': 5,
    '5': 6,
    '6': 7
}

z = pd.Series(dict_x) # using a dictionary to create a series results in the index taken the key labels 

z

1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

### Creating DataFrames

In [6]:
dict_x = {
    '1': (2,),
    '2': (3,),
    '3': 4,
    '4': 5,
    '5': 6,
    '6': 7
}

df_x = pd.DataFrame(dict_x) # if creating a Dataframe form a dictionary, the key names pass as columns

df_x

   1  2  3  4  5  6
0  2  3  4  5  6  7

In [7]:
df_pie = pd.DataFrame(['apple','blueberry','peach','cherry'])

df_pie

           0
0      apple
1  blueberry
2      peach
3     cherry

In [8]:
df_pie2 = pd.DataFrame(('apple','blueberry','peach','cherry'), index=['Mon','Tues','Wed','Thur']) # pie specials

df_pie2

              0
Mon       apple
Tues  blueberry
Wed       peach
Thur     cherry

### Creating a DataFrame from an imported File

In [9]:
ice_cream = pd.read_csv("sales_data.csv") # There are also functions for read_excel, read_json...

ice_cream

         Flavor  Scoops Sold Price Per Scoop Total Revenue
0       Vanilla           42           $2.50       $105.00
1     Chocolate           38           $2.50        $95.00
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
4    Rocky Road           19           $2.75        $52.25
5  Butter Pecan           14           $2.75        $38.50
6  Mango Sorbet           22           $3.00        $66.00
7  Cookie Dough           35           $3.00       $105.00

In [10]:
print(ice_cream)

         Flavor  Scoops Sold Price Per Scoop Total Revenue
0       Vanilla           42           $2.50       $105.00
1     Chocolate           38           $2.50        $95.00
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
4    Rocky Road           19           $2.75        $52.25
5  Butter Pecan           14           $2.75        $38.50
6  Mango Sorbet           22           $3.00        $66.00
7  Cookie Dough           35           $3.00       $105.00

### a Series is 1-dimensional, a DataFrame is 2D (columns and rows)

In [11]:
df_pie2.insert(1,"price",[2.99,3.99,3.50,3.50])

df_pie2

              0  price
Mon       apple   2.99
Tues  blueberry   3.99
Wed       peach   3.50
Thur     cherry   3.50

In [12]:
df_pie2.insert(0, 'allergens', ['wheat','wheat','wheat, nuts','gluten free, may contain traces of wheat']) # already accidentally

In [13]:
df_pie2

                                     allergens          0  price
Mon                                      wheat      apple   2.99
Tues                                     wheat  blueberry   3.99
Wed                                wheat, nuts      peach   3.50
Thur  gluten free, may contain traces of wheat     cherry   3.50

In [14]:
df_pie2.loc["Wed"]

allergens    wheat, nuts
0                  peach
price                3.5
Name: Wed, dtype: object

In [15]:
df_pie2.loc[[1]]

KeyError: "None of [Index([1], dtype='int64')] are in the [index]"

In [ ]:
df_pie2.iloc[[1]]

              0  price allergens
Tues  blueberry   3.99     wheat

In [ ]:
ice_cream[2:6]

         Flavor  Scoops Sold Price Per Scoop Total Revenue
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
4    Rocky Road           19           $2.75        $52.25
5  Butter Pecan           14           $2.75        $38.50

In [ ]:
ice_cream

         Flavor  Scoops Sold Price Per Scoop Total Revenue
0       Vanilla           42           $2.50       $105.00
1     Chocolate           38           $2.50        $95.00
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
4    Rocky Road           19           $2.75        $52.25
5  Butter Pecan           14           $2.75        $38.50
6  Mango Sorbet           22           $3.00        $66.00
7  Cookie Dough           35           $3.00       $105.00

In [ ]:
ice_cream.loc[9] = ["Birhtday Cake",np.nan, '$2.75',np.nan]

ice_cream

          Flavor Scoops Sold Price Per Scoop Total Revenue
0        Vanilla          42           $2.50       $105.00
1      Chocolate          38           $2.50        $95.00
2     Strawberry          27           $2.50        $67.50
3      Mint Chip          31           $2.75        $85.25
4     Rocky Road          19           $2.75        $52.25
5   Butter Pecan          14           $2.75        $38.50
6   Mango Sorbet          22           $3.00        $66.00
7   Cookie Dough          35           $3.00       $105.00
8  Birhtday Cake         NaN           $2.75           NaN
9  Birhtday Cake         NaN           $2.75           NaN

In [ ]:
# drop() on axis =0 will drop a roq, axis=1 will drop a column
ice_cream.drop(9, axis=0, inplace=True) # inplace defaults to False, must specify inplace= True to modify DataFrame in memory

ice_cream

          Flavor Scoops Sold Price Per Scoop Total Revenue
0        Vanilla          42           $2.50       $105.00
1      Chocolate          38           $2.50        $95.00
2     Strawberry          27           $2.50        $67.50
3      Mint Chip          31           $2.75        $85.25
4     Rocky Road          19           $2.75        $52.25
5   Butter Pecan          14           $2.75        $38.50
6   Mango Sorbet          22           $3.00        $66.00
7   Cookie Dough          35           $3.00       $105.00
8  Birhtday Cake         NaN           $2.75           NaN

In [ ]:
ice_cream.drop_duplicates() # for dropping duplicates dont call it

                      Flavor Scoops Sold Price Per Scoop Total Revenue
0                    Vanilla          42           $2.50       $105.00
1                  Chocolate          38           $2.50        $95.00
2                 Strawberry          27           $2.50        $67.50
3                  Mint Chip          31           $2.75        $85.25
4                 Rocky Road          19           $2.75        $52.25
5               Butter Pecan          14           $2.75        $38.50
6               Mango Sorbet          22           $3.00        $66.00
7               Cookie Dough          35           $3.00       $105.00
Birthday cake            NaN       $2.75             NaN           NaN
8              Birhtday Cake         NaN           $2.75           NaN

In [16]:
ice_cream

         Flavor  Scoops Sold Price Per Scoop Total Revenue
0       Vanilla           42           $2.50       $105.00
1     Chocolate           38           $2.50        $95.00
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
4    Rocky Road           19           $2.75        $52.25
5  Butter Pecan           14           $2.75        $38.50
6  Mango Sorbet           22           $3.00        $66.00
7  Cookie Dough           35           $3.00       $105.00

In [17]:
ice_cream.drop("Revenue Per Scoop", axis=1,inplace=True)

KeyError: "['Revenue Per Scoop'] not found in axis"

In [19]:
ic3 = ice_cream[ice_cream["Scoops Sold"] >= 25]
ic3

         Flavor  Scoops Sold Price Per Scoop Total Revenue
0       Vanilla           42           $2.50       $105.00
1     Chocolate           38           $2.50        $95.00
2    Strawberry           27           $2.50        $67.50
3     Mint Chip           31           $2.75        $85.25
7  Cookie Dough           35           $3.00       $105.00

In [ ]:
ice_cream.replace({'Flavor':{'Cookie Dough': 'Cookie Monster'}}, inplace= True) # defaults to inplace = False

In [23]:
ice_cream

           Flavor  Scoops Sold Price Per Scoop Total Revenue
0         Vanilla           42           $2.50       $105.00
1       Chocolate           38           $2.50        $95.00
2      Strawberry           27           $2.50        $67.50
3       Mint Chip           31           $2.75        $85.25
4      Rocky Road           19           $2.75        $52.25
5    Butter Pecan           14           $2.75        $38.50
6    Mango Sorbet           22           $3.00        $66.00
7  Cookie Monster           35           $3.00       $105.00

In [24]:
# .fillna() method can be used to provide a replacement value for NaN values

In [35]:
# replacing values using a loop

for i in ice_cream.index:
    if ice_cream.loc[i, 'Flavor'] == 'Vanilla':
        ice_cream.loc[i,'Price Per Scoop'] = 2.75
    elif ice_cream.loc[i,'Price Per Scoop'] == "$2.50":
        ice_cream.loc[i,'Price Per Scoop'] = 3.0
    elif ice_cream.loc[i,'Price Per Scoop'] == "$2.75":
        ice_cream.loc[i,'Price Per Scoop'] = 3.50
    elif ice_cream.loc[i,'Price Per Scoop'] == "$3.00":
        ice_cream.loc[i,'Price Per Scoop'] = 3.75 

ice_cream

           Flavor  Scoops Sold Price Per Scoop Total Revenue
0         Vanilla         42.0            2.75       $105.00
1       Chocolate         38.0             3.0        $95.00
2      Strawberry         27.0             3.0        $67.50
3       Mint Chip         31.0             3.5        $85.25
4      Rocky Road         19.0             3.5        $52.25
5    Butter Pecan         14.0             3.5        $38.50
6    Mango Sorbet         22.0            3.75        $66.00
7  Cookie Monster         35.0            3.75       $105.00
8   Birthday Cake          NaN             3.5           NaN

## Previewing data

In [31]:
ice_cream.head(3)

       Flavor  Scoops Sold Price Per Scoop Total Revenue
0     Vanilla           42            2.75       $105.00
1   Chocolate           38           $2.50        $95.00
2  Strawberry           27           $2.50        $67.50

In [32]:
ice_cream.tail()

           Flavor  Scoops Sold Price Per Scoop Total Revenue
3       Mint Chip           31           $2.75        $85.25
4      Rocky Road           19           $2.75        $52.25
5    Butter Pecan           14           $2.75        $38.50
6    Mango Sorbet           22           $3.00        $66.00
7  Cookie Monster           35           $3.00       $105.00

In [33]:
ice_cream.describe()

       Scoops Sold
count      8.00000
mean      28.50000
std        9.75412
min       14.00000
25%       21.25000
50%       29.00000
75%       35.75000
max       42.00000

In [34]:
ice_cream.loc[8] = ["Birthday Cake", np.nan, 3.50, np.nan]
ice_cream

           Flavor  Scoops Sold Price Per Scoop Total Revenue
0         Vanilla         42.0            2.75       $105.00
1       Chocolate         38.0           $2.50        $95.00
2      Strawberry         27.0           $2.50        $67.50
3       Mint Chip         31.0           $2.75        $85.25
4      Rocky Road         19.0           $2.75        $52.25
5    Butter Pecan         14.0           $2.75        $38.50
6    Mango Sorbet         22.0           $3.00        $66.00
7  Cookie Monster         35.0           $3.00       $105.00
8   Birthday Cake          NaN             3.5           NaN

In [38]:
ice_cream.describe() # describe does a quick statisctial summary

       Scoops Sold
count      8.00000
mean      28.50000
std        9.75412
min       14.00000
25%       21.25000
50%       29.00000
75%       35.75000
max       42.00000

In [39]:
ice_cream.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flavor           9 non-null      str
 1   Scoops Sold      8 non-null      float64
 2   Price Per Scoop  9 non-null      object
 3   Total Revenue    8 non-null      object
dtypes: float64(1), object(2), str(1)
memory usage: 420.0+ bytes

In [40]:
ice_cream['Price Per Scoop'] = ice_cream['Price Per Scoop'].astype(float)

ice_cream

           Flavor  Scoops Sold  Price Per Scoop Total Revenue
0         Vanilla         42.0             2.75       $105.00
1       Chocolate         38.0             3.00        $95.00
2      Strawberry         27.0             3.00        $67.50
3       Mint Chip         31.0             3.50        $85.25
4      Rocky Road         19.0             3.50        $52.25
5    Butter Pecan         14.0             3.50        $38.50
6    Mango Sorbet         22.0             3.75        $66.00
7  Cookie Monster         35.0             3.75       $105.00
8   Birthday Cake          NaN             3.50           NaN

In [41]:
ice_cream.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Flavor           9 non-null      str
 1   Scoops Sold      8 non-null      float64
 2   Price Per Scoop  9 non-null      float64
 3   Total Revenue    8 non-null      object
dtypes: float64(2), object(1), str(1)
memory usage: 420.0+ bytes

In [43]:
ice_cream.describe() # default behavior is to return stats on numeric columns only (unless there are none)

       Scoops Sold  Price Per Scoop
count      8.00000         9.000000
mean      28.50000         3.361111
std        9.75412         0.356000
min       14.00000         2.750000
25%       21.25000         3.000000
50%       29.00000         3.500000
75%       35.75000         3.500000
max       42.00000         3.750000

In [44]:
ice_cream.Flavor.describe()

count           9
unique          9
top       Vanilla
freq            1
Name: Flavor, dtype: object

In [45]:
ice_cream['Price Per Scoop'].value_counts()

Price Per Scoop
3.50    4
3.00    2
3.75    2
2.75    1
Name: count, dtype: int64

In [46]:
ice_cream['Flavor'].value_counts()

Flavor
Vanilla           1
Chocolate         1
Strawberry        1
Mint Chip         1
Rocky Road        1
Butter Pecan      1
Mango Sorbet      1
Cookie Monster    1
Birthday Cake     1
Name: count, dtype: int64

In [47]:
# back to the pie example
df_pie = pd.DataFrame(['apple','blueberry','peach','cherry'])
df_pie

           0
0      apple
1  blueberry
2      peach
3     cherry

In [49]:
df_pie['Daily Special'] = ['Mon','Tues','Wed','Thurs']

In [50]:
df_pie

           0 Daily Special
0      apple           Mon
1  blueberry          Tues
2      peach           Wed
3     cherry         Thurs

In [53]:
df_pie.rename(columns={0: "Flavor"}, inplace=True) # best if only want to rename one column or specific ones

In [54]:
df_pie

      Flavor Daily Special
0      apple           Mon
1  blueberry          Tues
2      peach           Wed
3     cherry         Thurs

In [55]:
# df_pie.columns = [] # have to rename all colums

## Working with  aggregation functioons

In [57]:
ice_cream

           Flavor  Scoops Sold  Price Per Scoop Total Revenue
0         Vanilla         42.0             2.75       $105.00
1       Chocolate         38.0             3.00        $95.00
2      Strawberry         27.0             3.00        $67.50
3       Mint Chip         31.0             3.50        $85.25
4      Rocky Road         19.0             3.50        $52.25
5    Butter Pecan         14.0             3.50        $38.50
6    Mango Sorbet         22.0             3.75        $66.00
7  Cookie Monster         35.0             3.75       $105.00
8   Birthday Cake          NaN             3.50           NaN

In [60]:
print(ice_cream['Scoops Sold'].sum())

228.0

In [62]:
ice_cream['Scoops Sold'].aggregate(["sum","mean","max","min"])

sum     228.0
mean     28.5
max      42.0
min      14.0
Name: Scoops Sold, dtype: float64

In [66]:
ice_cream[["Scoops Sold","Price Per Scoop"]].aggregate(["sum","mean"]).round(2)

      Scoops Sold  Price Per Scoop
sum         228.0            30.25
mean         28.5             3.36

In [65]:
ice_cream.agg({
    "Scoops Sold" : ["sum","mean"],
    "Price Per Scoop": ["mean", lambda x: x.max() - x.min()]
})

          Scoops Sold  Price Per Scoop
sum             228.0              NaN
mean             28.5         3.361111
<lambda>          NaN         1.000000

In [74]:
# using groupby

ice_cream.groupby(["Price Per Scoop"]).sum()

,Flavor,Scoops Sold,Total Revenue
Price Per Scoop,,,
2.75,Vanilla,42.0,$105.00
3.00,ChocolateStrawberry,65.0,$95.00$67.50
3.50,Mint ChipRocky RoadButter PecanBirthday Cake,64.0,$85.25$52.25$38.50
3.75,Mango SorbetCookie Monster,57.0,$66.00$105.00